name: ArgoCD CI webhook

on:
  workflow_run:
    workflows:
      - 'Docker Image CI'
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger upload only on the correct branch
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: |
          curl -XPOST -u "eol-vl:${{ secrets.CR_PAT }}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/eol-virtuallabx/edx-argocd/dispatches --data '{"event_type": "update-images", "client_payload": {"type": "norteamericano"}}'
